name: Code Analysis

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Lint PHP'
                        run: composer lint

                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'Coding Standard'
                        run: composer check-cs

                    -
                        name: 'Tests'
                        run: vendor/bin/phpunit

                    -
                        name: 'Rector'
                        run: vendor/bin/rector process src tests --dry-run --no-progress-bar

        name: ${{ matrix.actions.name }}

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            - uses: "ramsey/composer-install@v1"

            - run: ${{ matrix.actions.run }}
